name: Home Assistant validation

on:
  push:
  pull_request:
  schedule:
    - cron: "43 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: home-assistant/actions/hassfest@a7c616ce81ccda50150bf1595786c71b1883fabb # master 2026-08-16
  json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Validate JSON files
        run: python3 -c 'import json; from pathlib import Path; [json.loads(path.read_text()) for path in Path(".").rglob("*.json")]'
